resources "Material.io Style Guide" https://material.io/guidelines/style/color.html# "Very good colour and design advice for mobile and web applications" "material,style,colour,design,guidelines" --commit=false
resources "Colour Safe" http://colorsafe.co "Easy way to generate colour palettes for the web." "colour,design" --commit=false
resources "Abode Color Tool" https://color.adobe.com/create "Another great colour tool" "colour,adobe,design,tool" --commit=false
resources "Material Colour Tool" "https://material.io/resources/color/#!/?view.left=0&view.right=0" "Select colours for the web using this interactive colour tool." "colour,material,tool,pallette" --commit=false
resources "Website Mockup Generator" https://techsini.com/multi-mockup/index.php "Very cool tool to generate simple mockups of websites on various devices." "mockup,tool,design,nocode"
resources Crouton  https://github.com/dnschneid/crouton "From the README:\n\n>crouton is a set of scripts that bundle up into an easy-to-use,  Chromium OS-centric chroot generator. \n Basically a way to run native linux on a chromebook." "operating systems, chromium, linux"resources "Google Cloud Labs" https://cloud.google.com/training/free-labs/?utm_source=coursera&utm_medium=email&utm_campaign=GCP_comm_Jan2019 "These free labs take about 30 mins and introduce various technologies and services on the Google Cloud Platform." "google,cloud,tutorial,course"
resources Figma https://www.figma.com "Alternative to sketch" "graphic design,tool,wireframe" --commit=false
resources "Gravit Designer" https://designer.gravit.io "Mature designer software" "graphic design,tool" --commit=false
resources draw.io https://draw.io "Very robust drawing tool" "graphic design,drawing,wireframe,diagrams"
resources "Paypal Downshift" https://github.com/paypal/downshift "Primitives to build simple, flexible, WAI-ARIA compliant React autocomplete/dropdown/select/combobox components. This [blogpost](https://blog.kentcdodds.com/introducing-downshift-for-react-b1de3fca0817) explains it well." "tutorial,react,library"
resources GreenSock https://greensock.com "From the official site:\n\n> Ultra high-performance, professional-grade animation for the modern web" "animation,fewd" --commit=false
resources "Introduction to Statistical Learning" http://www-bcf.usc.edu/~gareth/ISL "From their website --> This book provides an introduction to statistical learning methods. It is aimed for upper level undergraduate students, masters students and Ph.D. students in the non-mathematical sciences. The book also contains a number of R labs with detailed explanations on how to implement the various methods in real life settings, and should be a valuable resource for a practicing data scientist." "statistics,machine learning,R,data science,logic" --commit=false
resources SticiGui https://www.stat.berkeley.edu/~stark/SticiGui/index.htm "From the University of California, Berkeley --> This text was written for a "terminal" introductory class in Statistics suitable students in Business, Communications, Economics, Psychology, Social Science, or liberal arts; that is, this is the first and last class in Statistics for most students who take it. It also covers logic and reasoning at a level suitable for a general education course." "data science,machine learning,statistics,book"
resources Kaggle https://www.kaggle.com "More than just Data sets. You have hosted jupyter notebooks and lots of examples of data analysis." "data,jupyter,machine learning,notebook" --commit=false
resources "Google Dataset Search" https://toolbox.google.com/datasetsearch "Fairly new service by Google for searching datasets for a wide variety of topics" "google,data,api" --commit=false
resources PDS https://pds.jpl.nasa.gov/datasearch/data-search/ "NASA's Planetary Data Service" "data,api,space,nasa"
resources "Evaluating Clustering Algorithms" http://www.ims.uni-stuttgart.de/institut/mitarbeiter/schulte/theses/phd/algorithm.pdf "Survey of clustering evaluation techniques with good summary of what evaluation means." "paper,algorithms,science,machine learning" --commit=false
resources "Knowledge Graph Refinement" http://www.semantic-web-journal.net/system/files/swj1167.pdf "A Survey of Approaches and Evaluation Methods" "paper,science,machine learning"
resources Tensorflow https://www.tensorflow.org/ "An open source library for building machine learning systems. The [Getting Started](https://www.tensorflow.org/get_started/) tutorial is very good." "tensorflow,google,machine learning,deep learning,neural networks,tutorial" --commit=false
resources "Intel Distribution for Python" https://software.intel.com/en-us/distribution-for-python "Highly optimized library for Machine Learning" "python,intel,machine learning,programming"
resources "Data School's ROC" http://www.dataschool.io/roc-curves-and-auc-explained "A few videos that explain ROC well" "video,tutorial,ROC,data science" --commit=false
resources "Data School" http://www.dataschool.io/15-hours-of-expert-machine-learning-videos "A full intro to the field of Data Science" "data science,school,tutorial" --commit=false
resources "Google's Machine Learning Glossary" https://developers.google.com/machine-learning/glossary "A beginner friendly glossary of terms used in ML" "google,machine learning,tutorial" --commit=false
resources "Google's Machine Learning Guides" https://developers.google.com/machine-learning/guides "Excellent ML guides with code examples." "google,tutorial,machine learning" --commit=false  
resources "Dealing with Text" https://www.analyticsvidhya.com/blog/2018/02/the-different-methods-deal-text-data-predictive-python "Article that gives quick overview of various text techniques" "article,text,python,machine learning" --commit=false
resources "Kaggle's Bag of Words Tutorial/Exercise" https://www.kaggle.com/c/word2vec-nlp-tutorial "This walkthrough explains using Bag of Words and other text processing techniques" "kaggle,machine learning,text,bag of words"    
resources React https://reactjs.org "A JavaScript library for building user interfaces" "library, javascript, react" --commit=false
resources "React Native" https://facebook.github.io/react-native "Create native apps for Android and iOS using React" "mobile, react, javascript, android, ios" --commit=false
resources Ink https://github.com/vadimdemedes/ink "Using React to build CLI views" "react, cli, library, ui, renderer" --commit=false
resources "React PDF" https://react-pdf.org "Render PDF documents to file or to the web with React" "react,renderer,pdf" --commit=false
resources Kyt https://github.com/nytimes/kyt "The New York Times React Starter" "react, starter" --commit=false
resources "React NodeGUI" https://react.nodegui.org "Build native GUI apps using React" "react,node, ui" --commit=false
resources Pastel https://github.com/vadimdemedes/pastel "Built on top of ink" "react ui cli colour" --commit=false
resources "React Spring" https://www.react-spring.io "Simple animation primitives" "react,spring,animation"
resources arXiv https://arxiv.org "From the Cornell University Library - Open access to 1,477,285 e-prints in Physics, Mathematics, Computer Science, Quantitative Biology, Quantitative Finance, Statistics, Electrical Engineering and Systems Science, and Economics" "research,science,papers" --commit=false
resources "Internet Archive" https://archive.org "An archive of millions of digital artifacts." "research,papers,science"
resources "How to GraphQL" https://www.howtographql.com "The free and open-source tutorial to learn all around GraphQL to go from zero to production.<br>Includes react-relay" "graphql,tutorial" --commit=false
resources CS50 "https://www.edx.org/course/cs50s-introduction-computer-science-harvardx-cs50x?inf_contact_key=48db6b8c9c1c95f472c86366d8c52425" "An introduction to the intellectual enterprises of computer science and the art of programming. Harvard University's EdX comp Sci offering for beginners." "computer science,course,harvard,edx,programming"
resources Electron https://electronjs.org/ "Build cross platform desktop apps with JS, HTML, CSS. Used by Slack, Discord and many others." "javascript,electron,desktop,tool" --commit=false
resources "CLI Cheatsheet" https://github.com/sw-yx/cli-cheatsheet/blob/master/README.md "List of tools for building CLIs." "cli,list,tutorial" --commit=false
resources Bazel https://www.bazel.build "A build tool from Google." "build,devops,google,tool" --commit=false
resources Docusaurus https://docusaurus.io/en "Open source documentation website used by all the greats. Based on React." "documentation,framework,react,open source" --commit=false
resources "AST Explorer" https://astexplorer.net "Examine the AST (Abstract Syntax Tree) generated by many different languages. Great for studying parsing and syntax." "AST,parsing,language,programming,tool,compiler,syntax" --commit=false
resources "Godbolt Compiler Explorer" https://godbolt.org "Examine the assembly code produced by many different compilers. Excellent tool for studying languages and compilers." "assembly,language,programming,compiler,syntax"
